"""领域数据准备与增强包（M5-D8）：一条**可持续更新**的领域数据流水线.

day048 的 ``finetune`` 包解决"这一批数据能不能用"，本包解决它的后半句：
"下一批来了怎么办"。六个阶段，顺序即策略::

    clean → quality → near_dedup → mixing → augment → freeze
    清洗     五维打分   两级去重       削峰     填谷      打指纹

模块划分（每个模块都能单独测试、单独理解）::

    fingerprint.py  shingle / Jaccard / MinHash 签名   —— 近重复的数学底座
    dedup.py        两级去重器（精确 + 近重复，可增量） —— 保留首次出现
    quality.py      五维质量打分（可解释、可排序）      —— 从布尔升级到连续分
    augment.py      四个增强算子（output 逐字不动）    —— 在小数据上扩样本
    mixing.py       配比上限（不动点迭代）+ 缺口报告   —— 治"某一组垄断"
    pipeline.py     六阶段编排 + 清单 + 增量合并       —— 可复现的版本链

与既有包的接缝刻意保持"单向依赖"：本包复用 ``finetune`` 的
``TrainingExample`` / ``DatasetCleaner`` / 采集器与切分落盘，
``finetune`` 一行都不需要知道本包的存在。因此 day048 的全部结论
（七条硬规则、unverified 证据链、可复现切分）在本包里依然成立，
本包只是在它们之后继续往下走。
"""

from __future__ import annotations

from smart_research_agent.domain_data.augment import (
    AUG_APPLIED,
    AUG_GUARD_REJECTED,
    AUG_NO_CHANGE,
    AUG_TAG_PREFIX,
    AUGMENT_OPS,
    CHINESE_RATIO_FLOOR,
    CONSTRAINTS,
    DEFAULT_MAX_PER_EXAMPLE,
    DEFAULT_OPS,
    LENGTH_CONSTRAINT_CHARS,
    OPS,
    PARAPHRASE_PAIRS,
    PREFIX_VARIANTS,
    AugmentationOutcome,
    AugmentOp,
    AugmentReport,
    ConstraintSpec,
    OpResult,
    augment_dataset,
    augment_example,
    augment_ops_table,
    augmented_ops,
    cjk_ratio,
    does_not_restate,
    is_augmented,
    is_mostly_chinese,
    render_augment_table,
    resolve_ops,
    transform_constraint,
    transform_noise,
    transform_paraphrase,
    transform_prefix,
    within_chars,
)
from smart_research_agent.domain_data.dedup import (
    DEFAULT_NEAR_DUP_THRESHOLD,
    STATUS_EXACT,
    STATUS_KEPT,
    STATUS_NEAR,
    DedupeDecision,
    DedupeReport,
    NearDuplicateIndex,
    dedupe_examples,
)
from smart_research_agent.domain_data.errors import DomainDataError
from smart_research_agent.domain_data.fingerprint import (
    DEFAULT_NUM_PERM,
    DEFAULT_SHINGLE_K,
    MINHASH_EMPTY,
    MINHASH_PRIME,
    MINHASH_SEED,
    Fingerprint,
    estimate_jaccard,
    exact_key,
    fingerprint_example,
    fingerprint_text,
    hash_shingle,
    jaccard_exact,
    minhash_signature,
    normalize_for_fingerprint,
    permutation_params,
    shingles,
)
from smart_research_agent.domain_data.mixing import (
    DEFAULT_GROUP_BY,
    DEFAULT_MAX_GROUP_RATIO,
    GROUP_BY_CHOICES,
    GROUP_BY_ORIGIN,
    GROUP_BY_SAFETY,
    GROUP_BY_SOURCE,
    GROUP_NORMAL,
    GROUP_SAFETY,
    GROUP_UNKNOWN,
    MIN_GROUP_KEEP,
    ORIGIN_AUGMENTED,
    ORIGIN_ORIGINAL,
    MixDeficit,
    MixingReport,
    MixPlan,
    apply_mix_plan,
    deficit_report,
    group_counts,
    group_key,
    mixing_scores,
    plan_mixing,
)
from smart_research_agent.domain_data.pipeline import (
    DATASET_FINGERPRINT_LENGTH,
    MANIFEST_FILENAME,
    SNAPSHOT,
    STAGE_ORDER,
    DomainDataManifest,
    DomainDataPipeline,
    DomainDataRun,
    StageRecord,
    dataset_fingerprint,
    default_pipeline,
)
from smart_research_agent.domain_data.quality import (
    DEFAULT_QUALITY_THRESHOLD,
    DIMENSIONS,
    LENGTH_HIGH,
    LENGTH_IDEAL_HIGH,
    LENGTH_IDEAL_LOW,
    LENGTH_LOW,
    REPETITION_BEST,
    REPETITION_NGRAM,
    REPETITION_WORST,
    STRUCTURE_MARKERS,
    STRUCTURE_OPEN_ENDED,
    STRUCTURE_WITH_MARKER,
    STRUCTURE_WITH_TERMINAL,
    TERMINAL_PUNCTUATION,
    QualityFilterResult,
    QualityScore,
    QualitySignals,
    QualityWeights,
    band_score,
    default_weights,
    descending_score,
    dimension_table,
    extract_signals,
    filter_by_quality,
    has_structure_marker,
    has_terminal_punctuation,
    ngram_repetition,
    quality_scores,
    render_dimension_table,
    score_example,
    structure_score,
    validate_threshold,
)

__all__ = [
    "AUGMENT_OPS",
    "AUG_APPLIED",
    "AUG_GUARD_REJECTED",
    "AUG_NO_CHANGE",
    "AUG_TAG_PREFIX",
    "CHINESE_RATIO_FLOOR",
    "CONSTRAINTS",
    "DATASET_FINGERPRINT_LENGTH",
    "DEFAULT_GROUP_BY",
    "DEFAULT_MAX_GROUP_RATIO",
    "DEFAULT_MAX_PER_EXAMPLE",
    "DEFAULT_NEAR_DUP_THRESHOLD",
    "DEFAULT_NUM_PERM",
    "DEFAULT_OPS",
    "DEFAULT_QUALITY_THRESHOLD",
    "DEFAULT_SHINGLE_K",
    "DIMENSIONS",
    "GROUP_BY_CHOICES",
    "GROUP_BY_ORIGIN",
    "GROUP_BY_SAFETY",
    "GROUP_BY_SOURCE",
    "GROUP_NORMAL",
    "GROUP_SAFETY",
    "GROUP_UNKNOWN",
    "LENGTH_CONSTRAINT_CHARS",
    "LENGTH_HIGH",
    "LENGTH_IDEAL_HIGH",
    "LENGTH_IDEAL_LOW",
    "LENGTH_LOW",
    "MANIFEST_FILENAME",
    "MINHASH_EMPTY",
    "MINHASH_PRIME",
    "MINHASH_SEED",
    "MIN_GROUP_KEEP",
    "OPS",
    "ORIGIN_AUGMENTED",
    "ORIGIN_ORIGINAL",
    "PARAPHRASE_PAIRS",
    "PREFIX_VARIANTS",
    "REPETITION_BEST",
    "REPETITION_NGRAM",
    "REPETITION_WORST",
    "SNAPSHOT",
    "STAGE_ORDER",
    "STATUS_EXACT",
    "STATUS_KEPT",
    "STATUS_NEAR",
    "STRUCTURE_MARKERS",
    "STRUCTURE_OPEN_ENDED",
    "STRUCTURE_WITH_MARKER",
    "STRUCTURE_WITH_TERMINAL",
    "TERMINAL_PUNCTUATION",
    "AugmentOp",
    "AugmentReport",
    "AugmentationOutcome",
    "ConstraintSpec",
    "DedupeDecision",
    "DedupeReport",
    "DomainDataError",
    "DomainDataManifest",
    "DomainDataPipeline",
    "DomainDataRun",
    "Fingerprint",
    "MixDeficit",
    "MixPlan",
    "MixingReport",
    "NearDuplicateIndex",
    "OpResult",
    "QualityFilterResult",
    "QualityScore",
    "QualitySignals",
    "QualityWeights",
    "StageRecord",
    "apply_mix_plan",
    "augment_dataset",
    "augment_example",
    "augment_ops_table",
    "augmented_ops",
    "band_score",
    "cjk_ratio",
    "dataset_fingerprint",
    "dedupe_examples",
    "default_pipeline",
    "default_weights",
    "deficit_report",
    "descending_score",
    "dimension_table",
    "does_not_restate",
    "estimate_jaccard",
    "exact_key",
    "extract_signals",
    "filter_by_quality",
    "fingerprint_example",
    "fingerprint_text",
    "group_counts",
    "group_key",
    "has_structure_marker",
    "has_terminal_punctuation",
    "hash_shingle",
    "is_augmented",
    "is_mostly_chinese",
    "jaccard_exact",
    "minhash_signature",
    "mixing_scores",
    "ngram_repetition",
    "normalize_for_fingerprint",
    "permutation_params",
    "plan_mixing",
    "quality_scores",
    "render_augment_table",
    "render_dimension_table",
    "resolve_ops",
    "score_example",
    "shingles",
    "structure_score",
    "transform_constraint",
    "transform_noise",
    "transform_paraphrase",
    "transform_prefix",
    "validate_threshold",
    "within_chars",
]
